### GET
GET http://localhost:8080/api/v1/beer
Accept: application/json

### GET by ID

GET http://localhost:8080/api/v1/beer/1bfe641b-6495-4a11-be54-3ad8fbedf972
Accept: application/json

### POST
POST http://localhost:8080/api/v1/beer
Content-Type: application/json
Accept: application/json

{
    "beerName": "New Beer",
    "beerStyle": "ALE",
    "upc": 123456,
    "price": 12.99,
    "quantityOnHand": 100
}
